steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'oscm-proxy', '.']
  dir:  'oscm-proxy'
images: ['oscm-proxy']
  
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'oscm-db', '.']
#  dir:  'oscm-db'
#images: ['oscm-proxy', 'oscm-db']

